services:
  - type: web
    name: prodhunt
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    autoDeploy: false
    envVars:
      - key: APP_NAME
        value: Prodhunt
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: sqlite
      - key: SESSION_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: CACHE_STORE
        value: database
